# Generated by Django 3.0.2 on 2020-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100, verbose_name='Produto')),
                ('quantidade_produto', models.IntegerField(verbose_name='Quantidade')),
                ('descricao_produto', models.TextField(verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
