# Generated by Django 3.0.2 on 2020-02-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='compra_produto',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Preco Compra'),
        ),
        migrations.AddField(
            model_name='produto',
            name='venda_produto',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Preco Venda'),
        ),
    ]
