# Generated by Django 3.0.3 on 2020-02-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_auto_20200206_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='compra_produto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preco Compra'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='venda_produto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preco Venda'),
        ),
    ]
