# Generated by Django 3.0.3 on 2020-02-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_auto_20200224_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m', verbose_name='Imagem Produto'),
        ),
    ]
