# Generated by Django 3.0.3 on 2020-02-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_produto_foto_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto_produto',
            field=models.ImageField(upload_to='imagens/%Y/%m', verbose_name='Imagem Produto'),
        ),
    ]
