# Generated by Django 3.0.2 on 2020-02-05 12:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaixaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baixa_quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('baixa_motivo', models.TextField(verbose_name='Motivo')),
                ('baixa_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('baixa_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto', verbose_name='Produto')),
            ],
        ),
    ]
