# Generated by Django 3.0.4 on 2020-03-15 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0005_auto_20200225_1405'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('entrada_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('entrada_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto', verbose_name='Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
    ]
