# Generated by Django 3.0.4 on 2020-03-15 10:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('produto', '0005_auto_20200225_1405'),
        ('entrada', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entrada',
            new_name='EntradaProduto',
        ),
    ]
