# Generated by Django 3.0.4 on 2020-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_auto_20200315_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradaproduto',
            name='entrada_motivo',
            field=models.TextField(null=True),
        ),
    ]
